kind: Service
apiVerion: v1
metadata:
   name: myservice
   labels:
       app: myspringbootapp
spec:
  selector:
    app: myspringbootapp
  type: LoadBalncer
  ports:
  - nodePort: 30036
    port: 80
    targetPort: 8080 
